---
plugins:
  - 'stylelint-order'
rules:
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  string-no-newline: true
  unit-no-unknown: true
  property-no-unknown: true
  keyframe-declaration-no-important: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  block-no-empty: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  media-feature-name-no-unknown: true
  comment-no-empty: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  color-named: 'never'
  length-zero-no-unit: true
  font-weight-notation: 'numeric'
  function-url-no-scheme-relative: true
  keyframes-name-pattern:
    - '^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$'
    -
      message: 'Please write key frames according to the BEM syntax, http://getbem.com/'
  number-max-precision: 2
  unit-blacklist:
    - 'cm'
    - 'mm'
    - 'in'
    - 'px'
    - 'pt'
    - 'pc'
    - 'ex'
    - 'ch'
  shorthand-property-no-redundant-values: true
  value-no-vendor-prefix: true
  property-no-vendor-prefix: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-no-important: true
  declaration-block-single-line-max-declarations: 1
  selector-class-pattern:
    - '^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$'
    -
      message: 'Please write class name according to the BEM syntax, http://getbem.com/'
  selector-max-empty-lines: 0
  selector-max-specificity: '0,3,0'
  selector-no-vendor-prefix: true
  selector-pseudo-element-colon-notation: 'double'
  media-feature-name-no-vendor-prefix: true
  at-rule-no-vendor-prefix: true
  max-nesting-depth: 3
  color-hex-case: 'upper'
  color-hex-length: 'long'
  function-comma-newline-after: 'never-multi-line'
  function-comma-newline-before: 'never-multi-line'
  function-comma-space-after: 'always'
  function-comma-space-before: 'never'
  function-max-empty-lines: 0
  function-name-case: 'lower'
  function-parentheses-newline-inside: 'never-multi-line'
  function-parentheses-space-inside: 'never'
  function-url-quotes: 'always'
  function-whitespace-after: 'always'
  number-leading-zero: 'always'
  number-no-trailing-zeros: true
  string-quotes: 'double'
  unit-case: 'lower'
  value-keyword-case: 'lower'
  value-list-comma-newline-after: 'never-multi-line'
  value-list-comma-newline-before: 'never-multi-line'
  value-list-comma-space-after: 'always'
  value-list-comma-space-before: 'never'
  value-list-max-empty-lines: 0
  property-case: 'lower'
  declaration-colon-space-after: 'always'
  declaration-colon-space-before: 'never'
  declaration-block-semicolon-newline-after: 'always'
  declaration-block-semicolon-newline-before: 'never-multi-line'
  declaration-block-semicolon-space-after: 'always-single-line'
  declaration-block-semicolon-space-before: 'never'
  declaration-block-trailing-semicolon: 'always'
  block-closing-brace-empty-line-before: 'never'
  block-closing-brace-newline-after: 'always'
  block-closing-brace-newline-before: 'always'
  block-closing-brace-space-after: 'always-single-line'
  block-closing-brace-space-before: 'always-single-line'
  block-opening-brace-newline-after: 'always'
  block-opening-brace-space-after: 'always-single-line'
  block-opening-brace-space-before: 'always'
  selector-attribute-brackets-space-inside: 'never'
  selector-attribute-operator-space-after: 'never'
  selector-attribute-operator-space-before: 'never'
  selector-attribute-quotes: 'never'
  selector-combinator-space-after: 'always'
  selector-combinator-space-before: 'always'
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: 'lower'
  selector-pseudo-class-parentheses-space-inside: 'always'
  selector-pseudo-element-case: 'lower'
  selector-type-case: 'lower'
  selector-list-comma-newline-after: 'never-multi-line'
  selector-list-comma-newline-before: 'never-multi-line'
  selector-list-comma-space-after: 'always'
  selector-list-comma-space-before: 'never'
  rule-empty-line-before: 'always'
  media-feature-colon-space-after: 'always'
  media-feature-colon-space-before: 'never'
  media-feature-name-case: 'lower'
  media-feature-parentheses-space-inside: 'always'
  media-feature-range-operator-space-after: 'always'
  media-feature-range-operator-space-before: 'always'
  media-query-list-comma-newline-after: 'never-multi-line'
  media-query-list-comma-newline-before: 'never-multi-line'
  media-query-list-comma-space-after: 'always'
  media-query-list-comma-space-before: 'never'
  at-rule-empty-line-before: 'always'
  at-rule-name-case: 'lower'
  at-rule-name-space-after: 'always'
  at-rule-semicolon-newline-after: 'always'
  at-rule-semicolon-space-before: 'never'
  comment-whitespace-inside: 'always'
  indentation: 4
  max-empty-lines: 2
  max-line-length: 80
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  no-empty-first-line: true
  unicode-bom: 'never'
  order/order:
    -
      - 'dollar-variables'
      - 'custom-properties'
      - 'at-rules'
      - 'declarations'
      -
        type: 'at-rule'
        name: 'supports'
      -
        type: 'at-rule'
        name: 'media'
      - 'rules'
  order/properties-order:
    -
      - 'content'
      - 'position'
      - 'top'
      - 'right'
      - 'bottom'
      - 'left'
      - 'z-index'
      - 'display'
      - 'vertical-align'
      - 'flex'
      - 'flex-grow'
      - 'flex-shrink'
      - 'flex-basis'
      - 'flex-direction'
      - 'flex-flow'
      - 'flex-wrap'
      - 'grid'
      - 'grid-area'
      - 'grid-template'
      - 'grid-template-areas'
      - 'grid-template-rows'
      - 'grid-template-columns'
      - 'grid-row'
      - 'grid-row-start'
      - 'grid-row-end'
      - 'grid-column'
      - 'grid-column-start'
      - 'grid-column-end'
      - 'grid-auto-rows'
      - 'grid-auto-columns'
      - 'grid-auto-flow'
      - 'grid-gap'
      - 'grid-row-gap'
      - 'grid-column-gap'
      - 'gap'
      - 'row-gap'
      - 'column-gap'
      - 'align-content'
      - 'align-items'
      - 'align-self'
      - 'justify-content'
      - 'justify-items'
      - 'justify-self'
      - 'order'
      - 'float'
      - 'clear'
      - 'object-fit'
      - 'overflow'
      - 'overflow-x'
      - 'overflow-y'
      - 'overflow-scrolling'
      - 'clip'
      #empty
      - 'box-sizing'
      - 'width'
      - 'min-width'
      - 'max-width'
      - 'height'
      - 'min-height'
      - 'max-height'
      - 'margin'
      - 'margin-top'
      - 'margin-right'
      - 'margin-bottom'
      - 'margin-left'
      - 'padding'
      - 'padding-top'
      - 'padding-right'
      - 'padding-bottom'
      - 'padding-left'
      - 'border'
      - 'border-spacing'
      - 'border-collapse'
      - 'border-width'
      - 'border-style'
      - 'border-color'
      - 'border-top'
      - 'border-top-width'
      - 'border-top-style'
      - 'border-top-color'
      - 'border-right'
      - 'border-right-width'
      - 'border-right-style'
      - 'border-right-color'
      - 'border-bottom'
      - 'border-bottom-width'
      - 'border-bottom-style'
      - 'border-bottom-color'
      - 'border-left'
      - 'border-left-width'
      - 'border-left-style'
      - 'border-left-color'
      - 'border-radius'
      - 'border-top-left-radius'
      - 'border-top-right-radius'
      - 'border-bottom-right-radius'
      - 'border-bottom-left-radius'
      - 'border-image'
      - 'border-image-source'
      - 'border-image-slice'
      - 'border-image-width'
      - 'border-image-outset'
      - 'border-image-repeat'
      - 'border-top-image'
      - 'border-right-image'
      - 'border-bottom-image'
      - 'border-left-image'
      - 'border-corner-image'
      - 'border-top-left-image'
      - 'border-top-right-image'
      - 'border-bottom-right-image'
      - 'border-bottom-left-image'
      #empty
      - 'background'
      - 'background-color'
      - 'background-image'
      - 'background-attachment'
      - 'background-position'
      - 'background-position-x'
      - 'background-position-y'
      - 'background-clip'
      - 'background-origin'
      - 'background-size'
      - 'background-repeat'
      - 'color'
      - 'box-decoration-break'
      - 'box-shadow'
      - 'outline'
      - 'outline-width'
      - 'outline-style'
      - 'outline-color'
      - 'outline-offset'
      - 'table-layout'
      - 'caption-side'
      - 'empty-cells'
      - 'list-style'
      - 'list-style-position'
      - 'list-style-type'
      - 'list-style-image'
      #empty
      - 'font'
      - 'font-weight'
      - 'font-style'
      - 'font-variant'
      - 'font-size-adjust'
      - 'font-stretch'
      - 'font-size'
      - 'font-family'
      - 'src'
      - 'line-height'
      - 'letter-spacing'
      - 'quotes'
      - 'counter-increment'
      - 'counter-reset'
      - '-ms-writing-mode'
      - 'text-align'
      - 'text-align-last'
      - 'text-decoration'
      - 'text-emphasis'
      - 'text-emphasis-position'
      - 'text-emphasis-style'
      - 'text-emphasis-color'
      - 'text-indent'
      - 'text-justify'
      - 'text-outline'
      - 'text-transform'
      - 'text-wrap'
      - 'text-overflow'
      - 'text-overflow-ellipsis'
      - 'text-overflow-mode'
      - 'text-shadow'
      - 'white-space'
      - 'word-spacing'
      - 'word-wrap'
      - 'word-break'
      - 'overflow-wrap'
      - 'tab-size'
      - 'hyphens'
      - 'interpolation-mode'
      #empty
      - 'opacity'
      - 'visibility'
      - 'filter'
      - 'resize'
      - 'cursor'
      - 'pointer-events'
      - 'user-select'
      #empty
      - 'unicode-bidi'
      - 'direction'
      - 'columns'
      - 'column-span'
      - 'column-width'
      - 'column-count'
      - 'column-fill'
      - 'column-gap'
      - 'column-rule'
      - 'column-rule-width'
      - 'column-rule-style'
      - 'column-rule-color'
      - 'break-before'
      - 'break-inside'
      - 'break-after'
      - 'page-break-before'
      - 'page-break-inside'
      - 'page-break-after'
      - 'orphans'
      - 'widows'
      - 'zoom'
      - 'max-zoom'
      - 'min-zoom'
      - 'user-zoom'
      - 'orientation'
      - 'fill'
      - 'stroke'
      #empty
      - 'transition'
      - 'transition-delay'
      - 'transition-timing-function'
      - 'transition-duration'
      - 'transition-property'
      - 'transform'
      - 'transform-origin'
      - 'animation'
      - 'animation-name'
      - 'animation-duration'
      - 'animation-play-state'
      - 'animation-timing-function'
      - 'animation-delay'
      - 'animation-iteration-count'
      - 'animation-direction'
      - 'animation-fill-mode'
    -
      unspecified: 'bottom'
