version: '2.4'
name: xpong
services:
    client:
        build:
            context: ../client
            dockerfile: ../docker/client.Dockerfile
        ports:
            - 3000:3000
    api:
        build:
            context: ../api
            dockerfile: ../docker/api.Dockerfile
        ports:
            - 4000:4000
